<a href="https://colab.research.google.com/github/Akhil8252/pytorch_learning/blob/main/001_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
print(torch.__version__)

2.1.0+cu121


<b> Pytorch tensor </b><br>
pytorch tensor can be created using torch.tensor

**pytorch scalar**

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

attributes of torch class

In [4]:
scalar.ndim # it gives the dimension of tensor
#scalar has no dimension or is a 0 degree tensor

0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
type(scalar)

torch.Tensor

vector

In [7]:
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [8]:
vector.ndim # for 1 degree tensor we need 1 pair of closing bracket

1

In [9]:
vector.item()#will give error as we are not dealing with a single scalar

RuntimeError: a Tensor with 3 elements cannot be converted to Scalar

In [10]:
vector.shape #here 3 simply denotes the no of column

torch.Size([3])

In [11]:
#MATRIX
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
#here we can see we have included 2 square brackets thus should have dimension as 2
matrix.ndim


2

In [13]:
#to access each element of matrix
matrix[0]

tensor([1, 2, 3])

In [14]:
matrix[0][1]

tensor(2)

In [15]:
matrix.shape#2 rows and 3 columns

torch.Size([2, 3])

In [16]:
Tensor = torch.tensor([[[2,4,6],[5,8, 7],[5, 8, 9]]])
Tensor

tensor([[[2, 4, 6],
         [5, 8, 7],
         [5, 8, 9]]])

In [17]:
Tensor.ndim

3

In [18]:
Tensor.shape

torch.Size([1, 3, 3])

#here 1 represents the bigger tensor(overall) or we can say one layer, 3 no of vectors inside the tensor and 2nd 3 represents no of elements in onen vector

In [19]:
Tensor[0]

tensor([[2, 4, 6],
        [5, 8, 7],
        [5, 8, 9]])

In [20]:
Tensor[0][1]

tensor([5, 8, 7])

#Random tensor

##Random tensors are important because the way NN starts learning they contains many random numbers in it like weights and biases

'start with random numbers - >look at the data -> update random numbers -> look at data -> update random numbers

In [21]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.7258, 0.9398, 0.3629, 0.9921],
        [0.4843, 0.1918, 0.1069, 0.4996],
        [0.2221, 0.5263, 0.1203, 0.8558]])

In [22]:
random_tensor1 = torch.rand(2,3,3,4)
random_tensor1

tensor([[[[0.6460, 0.2319, 0.8153, 0.1541],
          [0.3354, 0.0458, 0.4451, 0.4396],
          [0.7037, 0.0723, 0.5137, 0.1517]],

         [[0.1215, 0.2341, 0.9241, 0.3481],
          [0.7636, 0.7805, 0.3944, 0.0446],
          [0.5731, 0.9498, 0.5250, 0.0514]],

         [[0.9391, 0.7466, 0.2000, 0.4167],
          [0.5034, 0.8834, 0.3189, 0.7149],
          [0.6307, 0.7090, 0.5698, 0.4352]]],


        [[[0.1096, 0.8531, 0.5005, 0.8326],
          [0.9262, 0.1342, 0.6199, 0.1538],
          [0.2523, 0.3655, 0.7592, 0.4008]],

         [[0.2436, 0.3796, 0.7208, 0.8858],
          [0.5408, 0.5059, 0.3134, 0.8420],
          [0.4373, 0.1969, 0.4913, 0.3272]],

         [[0.4664, 0.6256, 0.5317, 0.2841],
          [0.6330, 0.7760, 0.9990, 0.5540],
          [0.8866, 0.8723, 0.2576, 0.2168]]]])

In [23]:
#create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size  = (3,224,224))
random_image_tensor#height width and color channel,,, color channel should always be first

tensor([[[0.0548, 0.1306, 0.6661,  ..., 0.4475, 0.8292, 0.9581],
         [0.3077, 0.0778, 0.4340,  ..., 0.8634, 0.8815, 0.5610],
         [0.2223, 0.0158, 0.7423,  ..., 0.9509, 0.6594, 0.7933],
         ...,
         [0.8242, 0.0622, 0.2703,  ..., 0.8974, 0.0874, 0.8680],
         [0.5389, 0.2259, 0.9043,  ..., 0.5504, 0.2509, 0.2847],
         [0.0993, 0.2969, 0.5265,  ..., 0.8979, 0.9533, 0.9302]],

        [[0.5941, 0.8434, 0.4836,  ..., 0.4402, 0.7487, 0.9269],
         [0.6963, 0.1725, 0.6154,  ..., 0.1029, 0.4321, 0.7522],
         [0.6286, 0.2773, 0.5456,  ..., 0.4297, 0.7460, 0.7249],
         ...,
         [0.9276, 0.8117, 0.9575,  ..., 0.9745, 0.6549, 0.5766],
         [0.7475, 0.7081, 0.5074,  ..., 0.1390, 0.1315, 0.2369],
         [0.6383, 0.0085, 0.7422,  ..., 0.9784, 0.7810, 0.8887]],

        [[0.5908, 0.6941, 0.7939,  ..., 0.9409, 0.0901, 0.0392],
         [0.3573, 0.0369, 0.7044,  ..., 0.5861, 0.2100, 0.1880],
         [0.0488, 0.4373, 0.5259,  ..., 0.7459, 0.3883, 0.

In [24]:
random_image_tensor.shape

torch.Size([3, 224, 224])

In [25]:
random_image_tensor1 = torch.rand(size  = (224,224,3))#deep learning library use this
random_image_tensor1

tensor([[[0.1324, 0.7815, 0.9239],
         [0.5552, 0.9220, 0.6933],
         [0.9460, 0.8221, 0.5970],
         ...,
         [0.2362, 0.0436, 0.1058],
         [0.5465, 0.3007, 0.3273],
         [0.2425, 0.4027, 0.2132]],

        [[0.8265, 0.1634, 0.0011],
         [0.2390, 0.4661, 0.8784],
         [0.4655, 0.8204, 0.3975],
         ...,
         [0.9635, 0.9409, 0.8388],
         [0.6853, 0.7499, 0.2146],
         [0.8278, 0.4580, 0.1548]],

        [[0.5706, 0.1762, 0.7579],
         [0.9776, 0.4614, 0.9158],
         [0.5800, 0.1838, 0.0898],
         ...,
         [0.6407, 0.0633, 0.4937],
         [0.6160, 0.4164, 0.4773],
         [0.9859, 0.0945, 0.0699]],

        ...,

        [[0.5265, 0.5692, 0.4818],
         [0.8104, 0.2288, 0.7357],
         [0.0637, 0.8476, 0.6884],
         ...,
         [0.4748, 0.4210, 0.3991],
         [0.7889, 0.0323, 0.3852],
         [0.6099, 0.7826, 0.3390]],

        [[0.5511, 0.7069, 0.9956],
         [0.6269, 0.4409, 0.5954],
         [0.

# we can or can't use size paremeter in torch.rand, its upto us
#####random_image_tensor1 = torch.rand(size  = (224,224,3)) and
#####random_image_tensor1 = torch.rand((224,224,3)) both are correct

#creating zeros and ones

In [26]:
zeros = torch.zeros(3,4) # 3 rows and 4 columns of zeros
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
#to check datatypes
zeros.dtype  #dtype stands for default datatype

torch.float32

In [28]:
ones = torch.ones(3,4) # 3 rows and 4 columns of zeros
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#create a range of tensors or tensors like

In [29]:
torch.range(1,10)

<ipython-input-29-a2647884754e>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [30]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
a = torch.arange(start = 0,end=1000, step=77)
a

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [32]:
#this can also be written as
a = torch.arange(0,1000,77)
a

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [33]:
# if want to create a tensor of shape equal to another tensor or we can say like tensors, we can use zeros_like method
ten_zeros = torch.zeros_like(input = a)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#tensor datatypes
####default datatypes in pytorch is float32,even if we write dtype =none

In [34]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,2.8,56])
float_32_tensor

tensor([ 3.0000,  2.8000, 56.0000])

In [35]:
float_32_tensor.dtype

torch.float32

In [36]:
float_32_tensor = torch.tensor([3.0,2.8,56],dtype=None)
float_32_tensor.dtype

torch.float32

In [37]:
float_32_tensor = torch.tensor([3.0,2.8,56],dtype=torch.float16)
float_32_tensor.dtype

torch.float16

In [38]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [39]:
#follow pytorch tensor datatype

In [40]:
#converting float32 to float16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [41]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

this should give error as we are multiplying two tensors with different precision i.e float32 and float 16.but this is giving right result.this is also an issue with pytorch. this will not give results always. for some operations this will result into error if datatypes are different.

In [42]:
#getting tensor information

# tensor data types : - tensor.dtype
# tensor shape :- tensor.shape
# on which device tensor is running:- tensor.device

In [43]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[4.4138e-01, 2.9933e-01, 3.6311e-04, 7.6098e-01],
        [1.9830e-02, 7.8565e-01, 1.3480e-01, 5.3025e-01],
        [4.7728e-01, 8.4442e-01, 2.9199e-01, 8.4022e-01]])

In [44]:
#finding details of some_tensor
print("datatype of tensor is {}:".format(some_tensor.dtype))
print(f"datatype of tensor is: {some_tensor.shape}")
print(f"datatype of tensor is: {some_tensor.device}")


datatype of tensor is torch.float32:
datatype of tensor is: torch.Size([3, 4])
datatype of tensor is: cpu


In [45]:
some_tensor.ndim

2

#manipulating tensor
 different operation on tensors
 1. addition
 2.subtraction
 3.multiplication
 4.division
 5.matrix multiplication

In [46]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [47]:
tensor*10

tensor([10, 20, 30])

In [48]:
#for multiplication we can use inbuilt function of pytorch.
torch.mul(tensor,10)

tensor([10, 20, 30])

In [49]:
torch.add(tensor,10)

tensor([11, 12, 13])

# matrix multiplication are of two types:
# 1. element wise multiplication
# 2. dot product

In [50]:
tensor = torch.tensor([1,2,3])

In [51]:
print(tensor,"*",tensor,"is")
print(tensor*tensor)#this gives us element wise multiplication

tensor([1, 2, 3]) * tensor([1, 2, 3]) is
tensor([1, 4, 9])


In [52]:
#Matrix multiplication
#   matmul is used for matrix multiplication

In [53]:
torch.matmul(tensor,tensor)

tensor(14)

In [54]:
torch.dot(tensor,tensor)#.dot is also used for matrix multiplication

tensor(14)

In [55]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)


tensor(14)
CPU times: user 2.3 ms, sys: 0 ns, total: 2.3 ms
Wall time: 5.12 ms


In [56]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 99 µs, sys: 0 ns, total: 99 µs
Wall time: 105 µs


tensor(14)

## one of the most common error in deep learning is shape error

### There are two rules while performing matrix multiplication

1. inner dimension should match
- `(3,2) @ (3,2)` won't work
- `(3,2) @ (2,3)` will work
- `(2,3) @ (3,2)` will work

** @ is also  used in matrix multipliocation

2. The resulting must have the outer dimension

* `(3,2) @ (2,3)`-> (3,3)


In [57]:
torch.matmul(torch.rand(3,4),torch.rand(4,3))

tensor([[0.5224, 0.4270, 0.6160],
        [1.4571, 1.2424, 1.2128],
        [1.8961, 1.3631, 1.5465]])

In [58]:
torch.rand(3,4)@torch.rand(4,3)

tensor([[0.6325, 0.2596, 0.3567],
        [1.7714, 0.8839, 1.1158],
        [1.4714, 1.1827, 1.1386]])

## shape for matrix multiplication

In [59]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [3,5],
                         [5,6]])

#torch.mm is also used for matrix multiplication , where mm is used as alias for matmul
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### to fix the issues related with shapes we use transpose

In [60]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[23, 13, 17],
        [53, 29, 39],
        [83, 45, 61]])

In [61]:
torch.matmul(tensor_A.T,tensor_B)

tensor([[41, 53],
        [56, 72]])

## finding min,max,mean etc (tensor aggregation)

In [62]:
import torch as th

In [64]:
x = th.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
#find the min(x)
th.min(x) , x.min()#both will give the result

(tensor(0), tensor(0))

In [67]:
th.max(x) , x.max()#both will give the result

(tensor(90), tensor(90))

In [68]:
#find the mean
th.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [69]:
x.dtype

torch.int64

In [74]:
#since x is an int64 datatype thus we need to convert it in a float32
#torch.mean() requires a tensor of float32 datatype
th.mean(x.type(th.float32)),x.type(th.float32).mean()

(tensor(45.), tensor(45.))

In [76]:
#find the sum
x.sum(),th.sum(x)

(tensor(450), tensor(450))

## positional min and max
### i.e the index at which min and max is there

In [77]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [78]:
torch.argmax(x)

tensor(9)

In [79]:
torch.argmin(x)

tensor(0)

In [83]:
x[0].item()

0

In [ ]:
## reshaping,stacking