<a href="https://colab.research.google.com/github/Akhil8252/pytorch_learning/blob/main/001_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
print(torch.__version__)

2.1.0+cu121


<b> Pytorch tensor </b><br>
pytorch tensor can be created using torch.tensor

**pytorch scalar**

In [3]:






scalar = torch.tensor(7)
scalar

tensor(7)

attributes of torch class

In [4]:
scalar.ndim # it gives the dimension of tensor
#scalar has no dimension or is a 0 degree tensor

0

In [5]:
#get tensor back as python int
scalar.item()

7

In [6]:
type(scalar)

torch.Tensor

vector

In [7]:
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [8]:
vector.ndim # for 1 degree tensor we need 1 pair of closing bracket

1

In [10]:
vector.item()#will give error as we are not dealing with a single scalar

RuntimeError: a Tensor with 3 elements cannot be converted to Scalar

In [11]:
vector.shape #here 3 simply denotes the no of column

torch.Size([3])

In [12]:
#MATRIX
matrix = torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [13]:
#here we can see we have included 2 square brackets thus should have dimension as 2
matrix.ndim


2

In [14]:
#to access each element of matrix
matrix[0]

tensor([1, 2, 3])

In [15]:
matrix[0][1]

tensor(2)

In [16]:
matrix.shape#2 rows and 3 columns

torch.Size([2, 3])

In [17]:
Tensor = torch.tensor([[[2,4,6],[5,8, 7],[5, 8, 9]]])
Tensor

tensor([[[2, 4, 6],
         [5, 8, 7],
         [5, 8, 9]]])

In [18]:
Tensor.ndim

3

In [19]:
Tensor.shape

torch.Size([1, 3, 3])

#here 1 represents the bigger tensor(overall) or we can say one layer, 3 no of vectors inside the tensor and 2nd 3 represents no of elements in onen vector

In [20]:
Tensor[0]

tensor([[2, 4, 6],
        [5, 8, 7],
        [5, 8, 9]])

In [21]:
Tensor[0][1]

tensor([5, 8, 7])

#Random tensor

##Random tensors are important because the way NN starts learning they contains many random numbers in it like weights and biases

'start with random numbers - >look at the data -> update random numbers -> look at data -> update random numbers

In [22]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0240, 0.2886, 0.2274, 0.2953],
        [0.6604, 0.4562, 0.4870, 0.0201],
        [0.7822, 0.8811, 0.1065, 0.6825]])

In [23]:
random_tensor1 = torch.rand(2,3,3,4)
random_tensor1

tensor([[[[4.6152e-01, 8.7341e-01, 4.2971e-01, 4.3289e-01],
          [4.8189e-01, 9.7415e-01, 2.9414e-01, 9.5397e-01],
          [5.9280e-02, 4.5021e-01, 1.0564e-01, 4.2870e-01]],

         [[2.3881e-01, 1.9999e-01, 1.9271e-01, 9.8555e-01],
          [1.1682e-01, 7.4514e-01, 6.2218e-01, 1.0383e-01],
          [2.9684e-01, 3.6733e-01, 9.4170e-01, 9.8714e-01]],

         [[5.8967e-02, 1.5975e-01, 4.1037e-01, 1.9570e-01],
          [6.3189e-01, 9.4387e-01, 2.2788e-01, 9.3992e-01],
          [5.4963e-01, 6.0115e-01, 2.3842e-06, 7.0950e-02]]],


        [[[4.7933e-02, 7.1200e-01, 7.0466e-01, 1.4446e-01],
          [3.7409e-01, 7.6803e-01, 1.7285e-01, 9.0521e-01],
          [8.9003e-01, 4.0002e-01, 9.8984e-02, 7.9216e-01]],

         [[2.0824e-01, 2.1624e-01, 1.3799e-01, 3.3587e-01],
          [5.0447e-01, 5.6502e-01, 8.3382e-01, 8.8317e-01],
          [4.9947e-01, 4.2396e-01, 2.4415e-01, 8.4557e-02]],

         [[4.8010e-01, 3.6565e-01, 8.8489e-02, 5.6638e-01],
          [7.5579e-01, 8.939

In [24]:
#create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size  = (3,224,224))
random_image_tensor#height width and color channel,,, color channel should always be first

tensor([[[0.2690, 0.0049, 0.2883,  ..., 0.7058, 0.9154, 0.5889],
         [0.6367, 0.4413, 0.5787,  ..., 0.7664, 0.1608, 0.5908],
         [0.4640, 0.6797, 0.8987,  ..., 0.7143, 0.9534, 0.5130],
         ...,
         [0.0073, 0.6807, 0.0824,  ..., 0.5912, 0.5160, 0.4580],
         [0.8351, 0.3101, 0.2362,  ..., 0.3464, 0.2020, 0.9757],
         [0.3392, 0.2263, 0.9290,  ..., 0.7080, 0.8438, 0.6473]],

        [[0.5109, 0.0481, 0.7751,  ..., 0.6332, 0.7710, 0.4758],
         [0.4344, 0.2530, 0.9309,  ..., 0.2845, 0.4300, 0.9451],
         [0.6129, 0.8529, 0.0838,  ..., 0.7664, 0.2360, 0.8523],
         ...,
         [0.1497, 0.7865, 0.6924,  ..., 0.5650, 0.5805, 0.3126],
         [0.2220, 0.0649, 0.6262,  ..., 0.1831, 0.4976, 0.3865],
         [0.3591, 0.5088, 0.7134,  ..., 0.1717, 0.4015, 0.0024]],

        [[0.9377, 0.0165, 0.1293,  ..., 0.2545, 0.4931, 0.3530],
         [0.2842, 0.3909, 0.4973,  ..., 0.7871, 0.1199, 0.7161],
         [0.9457, 0.6771, 0.1927,  ..., 0.3059, 0.4858, 0.

In [25]:
random_image_tensor.shape

torch.Size([3, 224, 224])

In [26]:
random_image_tensor1 = torch.rand(size  = (224,224,3))#deep learning library use this
random_image_tensor1

tensor([[[0.7091, 0.6325, 0.0536],
         [0.2895, 0.0737, 0.5727],
         [0.0967, 0.5506, 0.6734],
         ...,
         [0.7886, 0.9152, 0.1080],
         [0.5883, 0.4486, 0.9434],
         [0.7036, 0.9114, 0.2611]],

        [[0.1930, 0.3630, 0.8686],
         [0.7703, 0.7100, 0.3737],
         [0.5458, 0.4158, 0.1311],
         ...,
         [0.2616, 0.9091, 0.5468],
         [0.8411, 0.1674, 0.8300],
         [0.3283, 0.6152, 0.6403]],

        [[0.8279, 0.1185, 0.0269],
         [0.3966, 0.5154, 0.5956],
         [0.9362, 0.8415, 0.0470],
         ...,
         [0.8882, 0.9336, 0.2693],
         [0.5836, 0.0372, 0.6788],
         [0.5590, 0.1886, 0.6564]],

        ...,

        [[0.9385, 0.5714, 0.7638],
         [0.8983, 0.0176, 0.3429],
         [0.7648, 0.0029, 0.0636],
         ...,
         [0.7034, 0.5733, 0.5141],
         [0.7752, 0.5203, 0.9134],
         [0.8899, 0.0588, 0.8422]],

        [[0.2910, 0.3277, 0.7640],
         [0.8078, 0.3961, 0.8949],
         [0.

# we can or can't use size paremeter in torch.rand, its upto us
#####random_image_tensor1 = torch.rand(size  = (224,224,3)) and
#####random_image_tensor1 = torch.rand((224,224,3)) both are correct

#creating zeros and ones

In [27]:
zeros = torch.zeros(3,4) # 3 rows and 4 columns of zeros
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
#to check datatypes
zeros.dtype  #dtype stands for default datatype

torch.float32

In [29]:
ones = torch.ones(3,4) # 3 rows and 4 columns of zeros
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

#create a range of tensors or tensors like

In [30]:
torch.range(1,10)

<ipython-input-30-a2647884754e>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(1,10)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [31]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a = torch.arange(start = 0,end=1000, step=77)
a

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [33]:
#this can also be written as
a = torch.arange(0,1000,77)
a

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [34]:
# if want to create a tensor of shape equal to another tensor or we can say like tensors, we can use zeros_like method
ten_zeros = torch.zeros_like(input = a)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#tensor datatypes
####default datatypes in pytorch is float32,even if we write dtype =none

In [35]:
#float 32 tensor
float_32_tensor = torch.tensor([3.0,2.8,56])
float_32_tensor

tensor([ 3.0000,  2.8000, 56.0000])

In [36]:
float_32_tensor.dtype

torch.float32

In [37]:
float_32_tensor = torch.tensor([3.0,2.8,56],dtype=None)
float_32_tensor.dtype

torch.float32

In [38]:
float_32_tensor = torch.tensor([3.0,2.8,56],dtype=torch.float16)
float_32_tensor.dtype

torch.float16

In [39]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [40]:
#follow pytorch tensor datatype

In [41]:
#converting float32 to float16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [42]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

this should give error as we are multiplying two tensors with different precision i.e float32 and float 16.but this is giving right result.this is also an issue with pytorch. this will not give results always. for some operations this will result into error if datatypes are different.

In [43]:
#getting tensor information

# tensor data types : - tensor.dtype
# tensor shape :- tensor.shape
# on which device tensor is running:- tensor.device

In [44]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1938, 0.8444, 0.0537, 0.1047],
        [0.6288, 0.2380, 0.2552, 0.5222],
        [0.6941, 0.5565, 0.6710, 0.5614]])

In [45]:
#finding details of some_tensor
print("datatype of tensor is {}:".format(some_tensor.dtype))
print(f"datatype of tensor is: {some_tensor.shape}")
print(f"datatype of tensor is: {some_tensor.device}")


datatype of tensor is torch.float32:
datatype of tensor is: torch.Size([3, 4])
datatype of tensor is: cpu


In [46]:
some_tensor.ndim

2

#manipulating tensor
 different operation on tensors
 1. addition
 2.subtraction
 3.multiplication
 4.division
 5.matrix multiplication

In [47]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [48]:
tensor*10

tensor([10, 20, 30])

In [49]:
#for multiplication we can use inbuilt function of pytorch.
torch.mul(tensor,10)

tensor([10, 20, 30])

In [50]:
torch.add(tensor,10)

tensor([11, 12, 13])

# matrix multiplication are of two types:
# 1. element wise multiplication
# 2. dot product

In [51]:
tensor = torch.tensor([1,2,3])

In [52]:
print(tensor,"*",tensor,"is")
print(tensor*tensor)#this gives us element wise multiplication

tensor([1, 2, 3]) * tensor([1, 2, 3]) is
tensor([1, 4, 9])


In [53]:
#Matrix multiplication
#   matmul is used for matrix multiplication

In [54]:
torch.matmul(tensor,tensor)

tensor(14)

In [55]:
torch.dot(tensor,tensor)#.dot is also used for matrix multiplication

tensor(14)

In [56]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)


tensor(14)
CPU times: user 1.83 ms, sys: 0 ns, total: 1.83 ms
Wall time: 2.1 ms


In [57]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 78 µs, sys: 0 ns, total: 78 µs
Wall time: 83.2 µs


tensor(14)

## one of the most common error in deep learning is shape error

### There are two rules while performing matrix multiplication

1. inner dimension should match
- `(3,2) @ (3,2)` won't work
- `(3,2) @ (2,3)` will work
- `(2,3) @ (3,2)` will work

** @ is also  used in matrix multipliocation

2. The resulting must have the outer dimension

* `(3,2) @ (2,3)`-> (3,3)


In [58]:
torch.matmul(torch.rand(3,4),torch.rand(4,3))

tensor([[1.1572, 1.4835, 0.4395],
        [1.2163, 0.8800, 0.2364],
        [1.3533, 1.5846, 0.4745]])

In [59]:
torch.rand(3,4)@torch.rand(4,3)

tensor([[0.7502, 0.7798, 1.1630],
        [0.7681, 0.7116, 1.1892],
        [0.9201, 1.0680, 1.2358]])

## shape for matrix multiplication

In [61]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,8],
                         [3,5],
                         [5,6]])

#torch.mm is also used for matrix multiplication , where mm is used as alias for matmul
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

### to fix the issues related with shapes we use transpose

In [62]:
torch.matmul(tensor_A,tensor_B.T)

tensor([[23, 13, 17],
        [53, 29, 39],
        [83, 45, 61]])

In [63]:
torch.matmul(tensor_A.T,tensor_B)

tensor([[41, 53],
        [56, 72]])

## finding min,max,mean etc (tensor aggregation)

In [64]:
import torch as th

In [65]:
x = th.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [66]:
#find the min(x)
th.min(x) , x.min()#both will give the result

(tensor(0), tensor(0))

In [67]:
th.max(x) , x.max()#both will give the result

(tensor(90), tensor(90))

In [69]:
#find the mean
th.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [70]:
x.dtype

torch.int64

In [71]:
#since x is an int64 datatype thus we need to convert it in a float32
#torch.mean() requires a tensor of float32 datatype
th.mean(x.type(th.float32)),x.type(th.float32).mean()

(tensor(45.), tensor(45.))

In [72]:
#find the sum
x.sum(),th.sum(x)

(tensor(450), tensor(450))

## positional min and max
### i.e the index at which min and max is there

In [73]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [74]:
torch.argmax(x)

tensor(9)

In [75]:
torch.argmin(x)

tensor(0)

In [76]:
x[0].item()

0

## reshaping,stacking, squeezing and unsqueezing tensors
- Reshaping : - reshapes a tensor to desired shape
- view : - return a view of an input tensor of certain shape but keeps the same memory as originl tensor
- stacking : - combine multiple tensors ob the top of each other (vstack) or side by side(hstack)
- follow  "https://pytorch.org/docs/stable/generated/torch.vstack.html"
- squeeze : - remove all `1` dimensions from the tensor
- unsqueeze : - add a `1` dimension to a target tensor
- permute : - return a view of the input with dimensions permuted (swapped) in  a certain way

In [77]:
x = torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [79]:
x.reshape(1,7)# we can't squeeze 9 elements into 7

RuntimeError: shape '[1, 7]' is invalid for input of size 9

In [80]:
print(x.reshape(1,9)) #converted into a tensor having 1 row and 9 columns
print( x.shape[0])

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
9


In [81]:
x.reshape(9,1),x.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9]))

In [82]:
x.reshape(3,3)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

In [83]:
#change the view
z = x.view(1,9)

In [84]:
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

#### changing z changes x, because  a view of a tensor shares the same memory as the original

In [85]:
z[:,0] = 15
z , x# 1st element of both z and x have been changed

(tensor([[15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]]),
 tensor([15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]))

### stacking the tensor

In [86]:
#stack tensors on top of each other
x_stacked = torch.vstack([x,x,x,x]) # vstack means on the top of each other
x_stacked

tensor([[15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [87]:
x_stacked = torch.stack([x,x,x,x])# stack can be used for any sort of stacking
x_stacked

tensor([[15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [88]:
x_stacked = torch.stack([x,x,x,x],dim = 0)  # dimension 0 means vertical stack, this is the default
x_stacked

tensor([[15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
        [15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])

In [89]:
x_stacked = torch.stack([x,x,x,x],dim = 1) # dim 1  first reshapes the tensor and then stacking takes place
x_stacked

tensor([[15., 15., 15., 15.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.]])

In [90]:
x_stacked = torch.hstack([x,x,x,x])
x_stacked

tensor([15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 15.,  2.,  3.,  4.,  5.,
         6.,  7.,  8.,  9., 15.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 15.,
         2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.])

### seueeze and unsqueeze

In [91]:
# squeeze removes one dimension from the tensor i.e if there are 2 square brackets in the tensor this will remove one thus only one will be left
X = torch.arange(1,10)
X.shape

torch.Size([9])

In [92]:
print(f"previous x tensor is : {X}")
print(f"shape of  x tensor is : {X.shape }")
print(f"reshaped tensor is x_reshaped : { X.reshape(1,9)}")
print(f"shape of X_reshaped  is: {X.reshape(1,9).shape}")

print("after squeezing")
print(f"X_reshaped after squeezing is : { X.reshape(1,9).squeeze()}")
print(f"shape of X_reshaped after squeezing is : { X.reshape(1,9).squeeze().shape}")


previous x tensor is : tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
shape of  x tensor is : torch.Size([9])
reshaped tensor is x_reshaped : tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
shape of X_reshaped  is: torch.Size([1, 9])
after squeezing
X_reshaped after squeezing is : tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
shape of X_reshaped after squeezing is : torch.Size([9])


In [93]:
X_squeezed = X.reshape(1,9).squeeze()
print(f"previous x_squeezed tensor is : {X_squeezed }")
print(f"\nshape of  x_squeezed tensor is : {X_squeezed.shape }")

print("\nafter squeezing")
X_unsqueezed = X_squeezed.unsqueeze(dim=0)
print(f"\nX_unsqueezed  after unsqueezing is : { X_unsqueezed}")
print(f"shape of X_unsqueezed after unsqueezing is : { X_unsqueezed.shape}")

previous x_squeezed tensor is : tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

shape of  x_squeezed tensor is : torch.Size([9])

after squeezing

X_unsqueezed  after unsqueezing is : tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
shape of X_unsqueezed after unsqueezing is : torch.Size([1, 9])


In [94]:
X_unsqueezed = X_squeezed.unsqueeze(dim=1)
print(f"\nX_unsqueezed  after unsqueezing is : { X_unsqueezed}")
print(f"shape of X_unsqueezed after unsqueezing is : { X_unsqueezed.shape}")


X_unsqueezed  after unsqueezing is : tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])
shape of X_unsqueezed after unsqueezing is : torch.Size([9, 1])


In [95]:
### permute : - rearranges the dimensions of a target tensor in a specified order
x_original  = torch.rand(size = (224,224,3)) #[height,width,no of channels]
x_original

tensor([[[0.1348, 0.5848, 0.9986],
         [0.1549, 0.9625, 0.3557],
         [0.8464, 0.4321, 0.9553],
         ...,
         [0.3942, 0.1306, 0.5376],
         [0.8600, 0.9156, 0.2756],
         [0.7403, 0.3806, 0.9659]],

        [[0.6558, 0.2222, 0.8387],
         [0.7067, 0.8495, 0.1323],
         [0.0712, 0.1781, 0.7344],
         ...,
         [0.2114, 0.0270, 0.7075],
         [0.6087, 0.8413, 0.6058],
         [0.2985, 0.6810, 0.2485]],

        [[0.8675, 0.6015, 0.5801],
         [0.4153, 0.1205, 0.4522],
         [0.3097, 0.2793, 0.8254],
         ...,
         [0.3713, 0.3208, 0.7229],
         [0.1709, 0.8474, 0.9428],
         [0.1265, 0.4467, 0.8833]],

        ...,

        [[0.3911, 0.9797, 0.6557],
         [0.0932, 0.3352, 0.7268],
         [0.5970, 0.4058, 0.8032],
         ...,
         [0.4995, 0.3647, 0.3507],
         [0.1294, 0.2752, 0.9516],
         [0.5365, 0.8612, 0.9261]],

        [[0.8790, 0.1519, 0.5211],
         [0.1420, 0.1530, 0.0062],
         [0.

In [96]:
#permute this so that the no of channels will be the first, height will be the 2nd one and the width will be third one
x_permuted = x_original.permute(2,0,1)
x_permuted

tensor([[[0.1348, 0.1549, 0.8464,  ..., 0.3942, 0.8600, 0.7403],
         [0.6558, 0.7067, 0.0712,  ..., 0.2114, 0.6087, 0.2985],
         [0.8675, 0.4153, 0.3097,  ..., 0.3713, 0.1709, 0.1265],
         ...,
         [0.3911, 0.0932, 0.5970,  ..., 0.4995, 0.1294, 0.5365],
         [0.8790, 0.1420, 0.9525,  ..., 0.2915, 0.9973, 0.1264],
         [0.8177, 0.4150, 0.1084,  ..., 0.4023, 0.1679, 0.4720]],

        [[0.5848, 0.9625, 0.4321,  ..., 0.1306, 0.9156, 0.3806],
         [0.2222, 0.8495, 0.1781,  ..., 0.0270, 0.8413, 0.6810],
         [0.6015, 0.1205, 0.2793,  ..., 0.3208, 0.8474, 0.4467],
         ...,
         [0.9797, 0.3352, 0.4058,  ..., 0.3647, 0.2752, 0.8612],
         [0.1519, 0.1530, 0.1126,  ..., 0.9708, 0.2536, 0.7555],
         [0.9203, 0.8715, 0.1559,  ..., 0.7204, 0.7570, 0.3997]],

        [[0.9986, 0.3557, 0.9553,  ..., 0.5376, 0.2756, 0.9659],
         [0.8387, 0.1323, 0.7344,  ..., 0.7075, 0.6058, 0.2485],
         [0.5801, 0.4522, 0.8254,  ..., 0.7229, 0.9428, 0.

In [97]:
print(f"original shape:{x_original.shape}")
print(f"permuted shape:{x_permuted.shape}")

original shape:torch.Size([224, 224, 3])
permuted shape:torch.Size([3, 224, 224])


In [98]:
torch.randn(2,1,3)

tensor([[[-1.0485, -0.3147,  1.6914]],

        [[-2.2064,  1.2088, -0.3267]]])

In [99]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [100]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [101]:
x[0][0] # this can also be written in the form [0 0]

tensor([1, 2, 3])

In [102]:
x[0][0][0]

tensor(1)

In [103]:
x[0][0][0].item()

1

In [104]:
# we can use " : " to target all the dimensions
x[:,1]

tensor([[4, 5, 6]])

In [105]:
x[:,:,1]

tensor([[2, 5, 8]])

In [106]:
x[:,1,1]

tensor([5])

## pytorch tensor and numpy
- data in numpy to pytorch tensor - > `torch.from_numpy(ndarray)`
- pytorch tensor to numpy array - > `torch.Tensor.numpy()`
#### while converting from numpy array to pytorch tensor, pytorch reflects numpy's default datatype of float64 unless specified otherwise

In [125]:
import numpy as np
array = np.arange(1,8)
Tensor = torch.from_numpy(array)
array,array.dtype,Tensor, tensor.dtype

(array([1, 2, 3, 4, 5, 6, 7]),
 dtype('int64'),
 tensor([1, 2, 3, 4, 5, 6, 7]),
 torch.int64)

In [108]:
#changing the value of array, what will this do to the Tensor
array  = array+1
array,Tensor

(array([2, 3, 4, 5, 6, 7, 8]), tensor([1, 2, 3, 4, 5, 6, 7]))

In [109]:
#tensor to numpy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [110]:
tensor.dtype

torch.float32

### reproducibility : - Trying to take random out of random
in short hoe does a  neural network work?
`start with random numbers->tensor opeartions->update random number to try and make them better representation of the data ->again -> again -> again`

In [111]:
torch.rand(3,3)

tensor([[0.5711, 0.7879, 0.8847],
        [0.1207, 0.9928, 0.2794],
        [0.0035, 0.7805, 0.1350]])

##### to reduce the randomness in neural network and pycharm, we use the concept of
** random seed **.(so that same random no can be produced)
Essentially what the random seed does is "filavour " the randomness

In [112]:
random_seed = 42

torch.manual_seed(random_seed)
random_tensor_c = torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_D = torch.rand(3,4)

random_tensor_c,random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

### running tensors and pytorch on GPU
GPUs:- faster computation on numbers, cuda+NVIDIA
* Easiest :use google colab for free GPU (option to upgrade also
)
* use your own GPU:- takes some setup and requires the investment

*use cloud computing : - AWS,AZURE, GCP , allow us to use GPU on rental basis

*For above 2, pytorch+
GPU drivers(CUDA) take a little bit of setting , to do this refer the pytorch setup documentation

In [113]:
#check for GPU access with pytorch
torch.cuda.is_available()

False

In [114]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "CPU"
device

'CPU'

In [115]:
#count no of devices
torch.cuda.device_count()

0

#### visit pytorch device agnostics
* "https://pytorch.org/docs/stable/notes/cuda.html"
* since pytorch is capable to compute on GPU or CPU either. thus if available, use GPU else stick to default cpu

#### putting tensors and models on the GPU
* the reason, we want our computation to take place on GPU is that , it makes computation faster

In [116]:
#create a tensor
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [118]:
# move tensor to GPU(if available)
#since No GPU is available ,thus this will give an error
tensor_on_GPU = tensor.to(device)
tensor_on_GPU

RuntimeError: Expected one of cpu, cuda, ipu, xpu, mkldnn, opengl, opencl, ideep, hip, ve, fpga, ort, xla, lazy, vulkan, mps, meta, hpu, mtia, privateuseone device type at start of device string: CPU

In [122]:
##### moving tensors back to cpu
#if tensor is on GPU ,can't transform it to numpy
tensor_on_gpu.numpy()

NameError: name 'tensor_on_gpu' is not defined

In [123]:
#to fix the gpu tensor with numpy issue , we can set first it to CPU
tensor_back_on_cpu = tensor_on_gpu.cpu.numpy()
tensor_back_on_cpu

NameError: name 'tensor_on_gpu' is not defined

#### solve the excercises
* "https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises"